## Big Data Real-Time Analytics com Python e Spark

### Computação com Numpy

In [2]:
# Install or Lopad Package
import numpy as np

### Criando Estrutura de dados NumPy

In [3]:
# creating one-dimensional array
array1 = np.array([10, 20, 30, 40])

In [11]:
# creating two-dimensional array
array2 = np.array([[100, 83, 15], [42, 78, 0]])

In [5]:
array1

array([10, 20, 30, 40])

In [6]:
array2

array([[100,  83,  15],
       [ 42,  78,   0]])

In [7]:
# Check the array shape
array1.shape

(4,)

In [12]:
# Check the array shape
array2.shape

(2, 3)

In [13]:
# check the dimention
array2.ndim

2

## Em Python tudo é objeto

### Método - realiza no objeto
### Atributo - característica do objeto

In [15]:
# Method
array2.max()

100

In [16]:
# attribute
array2.ndim

2

## Criando estrtutura de dados com arange

In [18]:
array3 = np.arange(15)

In [19]:
array3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
# Using star/end (exclusive)
array4 = np.arange(0, 15, 5)

In [22]:
array4

array([ 0,  5, 10])

## Criando estrutura de dados com linspace

In [24]:
# Start, end, number of elements
array5 = np.linspace(0,3,4); array5

array([0., 1., 2., 3.])

## Criando estrutura de dados com outras funções

### numpy.zeros

In [25]:
# Array 10x8 of zero
array6 = np.zeros((10,8)); array6

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

### numpy.ones

In [26]:
# Array 2x3x2 de 1's 
array7 = np.ones((2,3,2)); array7

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

### numpy.eys

In [28]:
# Produces an identity matrix
array8 = np.eye(3); array8

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### numpy.diag

In [29]:
# Diagonal Matrix
array9 = np.diag((2,1,4,6)); array9

array([[2, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 6]])

### numpy.random.rand

In [30]:
# The function rand (n) produces  a sequence of uniform number distributed  with range from 0  to n
np.random.seed(100) # Set seed
array10 = np.random.rand(5) ; array10

array([0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886])

In [31]:
# The function randn (n) produces  a sequence of number with normal distribution
array11 = np.random.randn(5); array11

array([ 0.35467445, -0.78606433, -0.2318722 ,  0.20797568,  0.93580797])

### numpy.empty

In [32]:
array12 = np.empty((3,2)); array12

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

### numpy.tile

In [33]:
np.array([[9,4], [3,7]])

array([[9, 4],
       [3, 7]])

In [35]:
np.tile(np.array([[9,4], [3,7]]),4)

array([[9, 4, 9, 4, 9, 4, 9, 4],
       [3, 7, 3, 7, 3, 7, 3, 7]])

In [36]:
np.tile(np.array([[9,4], [3,7]]),(2,2))

array([[9, 4, 9, 4],
       [3, 7, 3, 7],
       [9, 4, 9, 4],
       [3, 7, 3, 7]])

## Tipos de Dados Numpy

In [38]:
array13 = np.array([8, -3, 5, 9], dtype = 'float') ; array13

array([ 8., -3.,  5.,  9.])

In [39]:
array13.dtype

dtype('float64')

In [40]:
array14 = np.array([2, 4, 6, 8]) ; array14

array([2, 4, 6, 8])

In [41]:
array14.dtype

dtype('int32')

In [42]:
array15 = np.array([2.0, 4, 6, 8]) ; array15

array([2., 4., 6., 8.])

In [43]:
array15.dtype

dtype('float64')

In [44]:
array16 = np.array(['Análise','de','Dados','com','Python']); array16

array(['Análise', 'de', 'Dados', 'com', 'Python'], dtype='<U7')

In [45]:
array17 = np.array([True, False, True]); array17

array([ True, False,  True])

In [46]:
array17.dtype

dtype('bool')

In [47]:
array18 = np.array([7, -3, 5.24]); array18

array([ 7.  , -3.  ,  5.24])

In [49]:
array18.dtype

dtype('float64')

In [50]:
array18.astype(int)

array([ 7, -3,  5])

## Operações com Arrays

In [55]:
# bArray starting at 0, with 30 elements and multiplication at 5
array19 = np.arange(0,30) * 5; array19

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125,
       130, 135, 140, 145])

In [56]:
array19 = np.arange(0,30); array19

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [58]:
# Raising an array to power
array20 = np.arange(5) ** 4; array20

array([  0,   1,  16,  81, 256], dtype=int32)

In [59]:
# Adding a number to each element of the array
array21 = np.arange(0,30) + 1; array21

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [65]:
# Operation between the arrays
array22 = np.arange(0, 30,3) + 3
array23 = np.arange(1,11)

In [62]:
array22

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [63]:
array23

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
# subtraction
array22 - array23

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [67]:
# Sum
array22 + array23

array([ 4,  8, 12, 16, 20, 24, 28, 32, 36, 40])

In [69]:
# Division
array22 / array23

array([3., 3., 3., 3., 3., 3., 3., 3., 3., 3.])

In [70]:
# Multiplication
array22 * array23

array([  3,  12,  27,  48,  75, 108, 147, 192, 243, 300])

In [71]:
# We can still compare arrays
array22 > array23

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [73]:
arr1 = np.array([True, False, True, False])
arr2 = np.array([False, False, True, False])
np.logical_and(arr1, arr2)

array([False, False,  True, False])

## Podemos criar array com Python, sem usar o módulo NumPy. Porém o NumPy é muito mais rápido

In [77]:
array_numpy = np.arange(100000)
%timeit array_numpy **4

357 µs ± 6.33 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [78]:
array_python = range(100000)
%timeit [array_python[i] ** 4 for i in array_python]

62.6 ms ± 483 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
